name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Sleeper team now run test!
        run: PLAYWRIGHT_JSON_OUTPUT_NAME="report.json" npx playwright test --reporter=json,line
        env:
          HOME: /root
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Report json
          path: report.json
          retention-days: 5
